export const projects = [
  {
    title: 'Siesa Customer Support',
    subtitle: 'Back-end',
    // description: "Portal de soporte para clientes, en el que pueden generar tickets y chats para la solución de problemas. Además del consumo de material y cursos virtuales de los aplicativos.",
    description: "Customer support portal, where they can generate tickets and chats for problem solving. In addition to the consumption of material and virtual courses of the applications.",
    image: 'https://i.ibb.co/QJ0LcYP/4.png',
    tags: ['PHP', 'jQuery', 'MySQL', 'WordPress'],
    code: '',
    visit: 'https://www.siesacustomersupport.com',
    id: 0,
  },
  {
    title: 'miSiesa',
    subtitle: 'Back-end',
    // description: "Intranet creada para los colaboradores de la compañía, en la que pueden consumir información relacionada con la empresa e interactuar a modo de red social con el contenido publicado.",
    description: "Intranet created for the company's collaborators, in which they can consume information related to the company and interact as a social network with the published content.",
    image: 'https://i.ibb.co/GFT2vZv/5.png',
    tags: ['PHP', 'jQuery', 'SQL Server', 'WordPress'],
    code: '',
    visit: 'https://www.misiesa.com',
    id: 1,
  },
  {
    title: 'GB Media Group',
    subtitle: 'Web Design',
    // description: "Grupo empresarial que presta los servicios de creación y desarrollo de negocios online, producción audiovisual, imágen corporativa, entre otras.",
    description: "Business group that provides online business creation and development services, audiovisual production, corporate image, among others.",
      image: 'https://i.ibb.co/Lt7wKk6/1.png',
      tags: ['HTML', 'CSS', 'JavaScript', 'PHP'],
    code: '',
    visit: 'https://gbmediagroup.com/',
    id: 2,
  },
  {
    title: 'Penthouse Studio',
    subtitle: 'Web Design',
    // description:"Estudio de modelos que hace parte del grupo empresarial con una amplia y reconocida trayectoria en la industria webcam de Colombia.",
    description:"Study of models that is part of the business group with a wide and recognized trajectory in the Colombian webcam industry.",
    image: 'https://i.ibb.co/2vCzs1j/2.png',
    tags: ['HTML', 'CSS', 'JavaScript', 'PHP'],
    code: '',
    visit: 'https://www.estudioph.grupo-bedoya.com/',
    id: 3,
  },
  {
    title: 'VipStudio',
    subtitle: 'Web Design',
    description: "Study of models that is part of the business group with a wide and recognized trajectory in the Colombian webcam industry.",
      image: 'https://i.ibb.co/gtZBT9f/3.png',
      tags: ['HTML', 'CSS', 'JavaScript', 'PHP'],
    code: '',
    visit: 'https://vipstudiocali.com/',
    id: 4,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Lorem ipsum ipsum', },
  { year: 2018, text: 'Lorem ipsum lorem ipsum ipsum', },
  { year: 2019, text: 'Lorem ipsum lorem ipsum', },
  { year: 2020, text: 'Lorem ipsum lorem ipsum ipsum ma', },
  { year: 2021, text: 'Lorem ipsum lorem ipsum', },
];